### ISSUE TITLE
'quote_plus' call for request body causes performance problem

### ISSUE THREAD

**Issue by musou1500** [pbogut/deoplete-padawan#14]
Hello.
I noticed sometimes padawan.php server response is too slow.
But, when I use sublime version plugin, padawan responses fast.
So, I compared these plugin's request by using tcpdump.
And I remove [quote_plus call](https://github.com/pbogut/deoplete-padawan/blob/master/rplugin/python3/deoplete/sources/deoplete_padawan/padawan_server.py#L53), then padawan server became responses fast.

But I struggling to research why padawan's response to be slow when I use quote_plus.
Do you have some idea?

**Comment by pbogut** [comment]
Hi @musou1500, 
I'm trying to reproduce your problem and to be honest, I can't see any response difference. However, quote_plus seems to be redundant anyway, as everything is working perfectly fine without it. Plus encoded request is bigger and maybe that is causing an issue for you.

If you want to submit a pull request, I'm happy to merge it.

**Comment by musou1500** [comment]
Thank you.
I'll give it a try to find out cause of this issue, because it may be padawan.php's issue.
