### ISSUE TITLE
Getting connection timeout when trying to autocomplete php file

### ISSUE THREAD

**Issue by mwildehahn** [pbogut/deoplete-padawan#15]
I'm getting the following error when trying to autocomplete:

```
Connection to padawan.php timed out
```

From the log I'm seeing this when I run start/stop/start padawan server, so it seems like it is running correctly:
```
$ tail -f /tmp/padawan-server.log
Started http server on 127.0.0.1:15155
POST /kill
Started http server on 127.0.0.1:15155
```

but i don't see anything else being logged.

anything i can do to debug more? i'm new to php/padawan.

**Comment by mwildehahn** [comment]
Not sure if this is helpful, but I'm seeing this too:

```
$ http POST 127.0.0.1:15155/kill

http: error: ConnectionError: ('Connection aborted.', BadStatusLine("''",)) while doing POST request to URL: http://127.0.0.1:15155/kill
```

**Comment by mwildehahn** [comment]
hm, it looks like it might be an issue with the size of the file, the file i was doing it on was over a couple thousand lines. 

it looks like it is working on a smaller file:

```
POST /complete
[2016-11-30 07:43:42] completer.DEBUG: 2.598762512207E-5 seconds for ast processing [] []
[2016-11-30 07:43:42] completer.DEBUG: Found token '' with type 2048 [] []
[2016-11-30 07:43:42] completer.DEBUG: 0.00047588348388672 seconds for entries generation [] []
Response time: 0.00066304206848145```

**Comment by mwildehahn** [comment]
so i had a bunch of issues, for future travelers:

- set `minimum-stability` to `dev` in composer
- install padawan with dev-master: `composer global require mkusher/padawan:dev-master`
- generate the padawan index with `padawan generate`
- then things started to work for smaller files

for large files, i'm still getting the timeout. i'm working on a somewhat legacy code base that has some files with thousands of lines. is this a known limit? or is there anything i can do to increase the timeout etc?

**Comment by pbogut** [comment]
Hi @mhahn, I think this is padawan issue, a few hours ago I've created [issue#71](https://github.com/mkusher/padawan.php/issues/71) there. With the problem, I was experiencing (and I believe you have the same issue) timeout increasing won't help.

**Comment by mwildehahn** [comment]
thanks @pbogut, i actually just saw that as i was digging into this. i'll close this but just wanted to jot down my notes.
