### ISSUE TITLE
re-generate index after save

### ISSUE THREAD

**Issue by musou1500** [pbogut/deoplete-padawan#17]
This program seems not to generate index when files are updated.
Is it possible to re-generate index on 'BufWritePost'?

thank you.

**Comment by pbogut** [comment]
I'am afraid it's currently not possible. AFAIK padawan is updating file when you try to get an autocompletion in that file. There was attempt to add `update` action, but not sure if that's working now. If so then I may be able to add it to the plugin. @mkusher?

**Comment by mkusher** [comment]
@pbogut update should work on latest padawan, so there could be an option to enable such behaviour, I think

**Comment by musou1500** [comment]
@pbogut 
In some case, I could not get enough completion candidates.
So I posted the this issue.
Here is steps to reproduce it.
1. "composer.phar init"
2. create 2 php classes which has some methods.
3. exit padawan-server
4. try to complete method name of a created class on another class.(but completion does not works)

@mkusher 
I looked around a padawan.php code.
"update" command seems not to rewrite index of the part of a file, if it was not updated.
So I think using it is better way than using "generate" command.

May I create PR?

**Comment by mkusher** [comment]
yes, you should definitely use update command, not generate. And yes, PR are welcome!)

**Comment by musou1500** [comment]
@mkusher 
Thank you. I opened PR.

**Comment by pbogut** [comment]
Solved in #18
