### ISSUE TITLE
Work without composer.json?

### ISSUE THREAD

**Issue by geekjam** [pbogut/deoplete-padawan#23]

**Comment by pbogut** [comment]
Sorry, what?

**Comment by geekjam** [comment]
It doesn't work on single php file.

**Comment by pbogut** [comment]
Yes it does. If you want to report something or get help then try to put more information here.

Did you install padawan.php server? Is it started? What does server logs say? And how this PHP file looks like? Can you give us minimum not working example so I can try it myself?

**Comment by geekjam** [comment]
Only project
