### ISSUE TITLE
Fuzzy completion for class is broken

### ISSUE THREAD

**Issue by pbogut** [pbogut/deoplete-padawan#6]
Given:

```
namespace This\Is\Name\Space;
```

When:

```
use This\Is\Sp|
```

Should recommend full namespace, instead you have to type:

```
use This\Is\NamSp|
```

That's because input position is set right after backslash instead of beginning of the name space.

**Comment by mkusher** [comment]
@pbogut it looks more like bug in padawan itself

**Comment by pbogut** [comment]
@mkusher it's not, padawan is showing completion for the remaining part of the namespace and that's all right. The problem here is that deoplete is not asking padawan for completion until 2 (or 3) characters of the namespace part are provided, then padawan can't recommend anything as there is no match. I can either set cursor on `use |` position or trigger deoplete completion stright after `\`. Padawan then should return all data, and deoplete will take care of fuzzy match.
